[versions]
postgres-driver = "42.7.8"
hikari = "7.0.1"

[libraries]
hikari = {module = "com.zaxxer:HikariCP", version.ref = "hikari"}
postgres-driver = {module ="org.postgresql:postgresql", version.ref = "postgres-driver"}

[plugins]