[versions]
postgres-driver = "42.7.10"
hikari = "7.0.2"

### Spring
spring-boot = "3.5.4"
spring-dependency-management = "1.1.7"

[libraries]
hikari = {module = "com.zaxxer:HikariCP", version.ref = "hikari"}
postgres-driver = {module ="org.postgresql:postgresql", version.ref = "postgres-driver"}

### Spring
spring-boot-starter = {module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot"}
spring-boot-starter-jdbc = {module = "org.springframework.boot:spring-boot-starter-jdbc", version.ref = "spring-boot"}
spring-boot-autoconfigure = {module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot"}
spring-boot-configuration-processor = {module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "spring-boot"}
spring-boot-starter-test = {module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring-boot"}

[plugins]
spring-boot = {id = "org.springframework.boot", version.ref = "spring-boot"}
spring-dependency-management = {id = "io.spring.dependency-management", version.ref = "spring-dependency-management"}